# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build a cached tree adjacency structure
#'
#' @param edge Integer matrix, the tree's edge matrix
#' @return An external pointer to the cached structure
#' @export
rcpp_buildTree <- function(edge, root) {
    .Call(`_phylowise_rcpp_buildTree`, edge, root)
}

#' Get leaf descendants using a cached tree structure
#'
#' @param tree_ptr External pointer from rcpp_buildTree()
#' @param node Integer node ID
#' @param nleaves Integer number of leaves
#' @return Integer vector of descendant node IDs
#' @export
rcpp_getDescendantsFast <- function(tree_ptr, node, nleaves) {
    .Call(`_phylowise_rcpp_getDescendantsFast`, tree_ptr, node, nleaves)
}

#' Get leaves that are NOT descendants using a cached tree structure
#'
#' @param tree_ptr External pointer from rcpp_buildTree()
#' @param node Integer node ID
#' @param nleaves Integer number of leaves
#' @return Integer vector of descendant node IDs
#' @export
rcpp_getNonDescendantsFast <- function(tree_ptr, node, nleaves) {
    .Call(`_phylowise_rcpp_getNonDescendantsFast`, tree_ptr, node, nleaves)
}

#' Get the path between two nodes in a tree
rcpp_nodepathFast <- function(tree_ptr, from, to) {
    .Call(`_phylowise_rcpp_nodepathFast`, tree_ptr, from, to)
}

#' Fast MRCA using cached depth + parent lookup
#'
#' @param tree_ptr External pointer from rcpp_buildTree()
#' @param a Integer node ID (e.g. tip index)
#' @param b Integer node ID (e.g. tip index)
#' @return Integer node ID of the most recent common ancestor
#' @export
rcpp_getMRCA <- function(tree_ptr, a, b) {
    .Call(`_phylowise_rcpp_getMRCA`, tree_ptr, a, b)
}

