


#' Build a distance matrix from a tree (time tree or substitution tree)
#'
#'
#' @param tree a tree (phylo object)
#' @return A distance matrix, where dij is the mean distance from leaf i and j to their ancestor 
#' @examples
#' # Sample a coalescent tree with 10 taxa and then build a distance matrix
#' tree <- ape::rcoal(10)
#' dmat <- getDistanceMatrix(tree)
#' @export
getDistanceMatrix = function(tree) {
	
 	if (!inherits(tree, "phylo")) {
		stop("Input must be a phylo object!")
	}
  
  tips = tree$tip.label
  n = length(tips)
  
  # Node depths measured from tips
  node_depths_tips = ape::node.depth.edgelength(tree)
  
  dists = matrix(0, nrow=n, ncol=n)
  rownames(dists)=tips
  colnames(dists)=tips
  
  row.num=1
  for (i in 1:(n-1)) {
    for (j in (i+1):n) {
      mrca_node = ape::getMRCA(tree, c(i, j))
      distance = sum(node_depths_tips[c(i,j)] - node_depths_tips[mrca_node]) / 2
      dists[i,j] = distance
      dists[j,i] = distance
    }
  }
 
  dists

}





#' Read a single summary tree or a posterior distribution of annotated nexus trees generated by the 
#' BEAST software suites, and apply burn-in.  Built on top of the phylotate::read_annotated function.
#'
#'
#' @param nexus.file a nexus file
#' @param burnin proportion of burn-in to apply to the file (default: 0.1)
#' @return A list of trees
#' @examples
#' # Read in the small mammal.trees file generated by BEAST, available in the phylowise package
#' treefile <- system.file("extdata", "mammals.trees", package = "phylowise")
#' trees <- readBeastTrees(treefile, burnin=0)
#' tree1 <- trees[[1]]
#' plot(tree1)
#' print(tree1$node.comment)
#' @export
readBeastTrees = function(nexus.file, burnin=0.1) {
  

  # First we read in the lines and correct formatting issues that commonly occur during MCMC
  tree1 = readLines(nexus.file, warn=F)
  if (tree1[length(tree1)] != "End;"){
    tree1 = c(tree1, "End;")
  }

  tmpFile = paste0(tempdir(), "/tmp.", floor(runif(1, 100000, 100000000)), ".nexus")
  while (file.exists(tmpFile)){
    tmpFile = paste0(tempdir(), "/tmp.", floor(runif(1, 100000, 100000000)), ".nexus")
  }

  write(paste(tree1, collapse = "\n"), tmpFile)

  ## Load tree
  trees = tryCatch({
      phylotate::read_annotated(tmpFile, format="nexus")
  }, error = function(e) {
     file.remove(tmpFile)
     stop(paste("Encountered error opening file:", e))
  })
  

  # Delete temporary file
  file.remove(tmpFile)


  if (inherits(trees, "phylo")) {
    trees.burnin = list(trees)
  }else{


    trees.burnin = list()
    if (length(trees) > 1 & burnin > 0){
      b = ceiling(burnin * length(trees)):length(trees)
      if (b[1] == 0){
        b = b[-1]
      }
      
      j=1
      for (i in b){
        trees.burnin[[j]] = trees[[i]]
        j = j + 1
      }
      trees.burnin
    }else{
      trees.burnin[[1]] = trees
    }
  

  }

  trees.burnin

}



