// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_buildTree
SEXP rcpp_buildTree(IntegerMatrix edge, int root);
RcppExport SEXP _phylowise_rcpp_buildTree(SEXP edgeSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_buildTree(edge, root));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_getDescendantsFast
IntegerVector rcpp_getDescendantsFast(SEXP tree_ptr, int node, int nleaves);
RcppExport SEXP _phylowise_rcpp_getDescendantsFast(SEXP tree_ptrSEXP, SEXP nodeSEXP, SEXP nleavesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type nleaves(nleavesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_getDescendantsFast(tree_ptr, node, nleaves));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_getNonDescendantsFast
IntegerVector rcpp_getNonDescendantsFast(SEXP tree_ptr, int node, int nleaves);
RcppExport SEXP _phylowise_rcpp_getNonDescendantsFast(SEXP tree_ptrSEXP, SEXP nodeSEXP, SEXP nleavesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type nleaves(nleavesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_getNonDescendantsFast(tree_ptr, node, nleaves));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nodepathFast
IntegerVector rcpp_nodepathFast(SEXP tree_ptr, int from, int to);
RcppExport SEXP _phylowise_rcpp_nodepathFast(SEXP tree_ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nodepathFast(tree_ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_getMRCA
int rcpp_getMRCA(SEXP tree_ptr, int a, int b);
RcppExport SEXP _phylowise_rcpp_getMRCA(SEXP tree_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree_ptr(tree_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_getMRCA(tree_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phylowise_rcpp_buildTree", (DL_FUNC) &_phylowise_rcpp_buildTree, 2},
    {"_phylowise_rcpp_getDescendantsFast", (DL_FUNC) &_phylowise_rcpp_getDescendantsFast, 3},
    {"_phylowise_rcpp_getNonDescendantsFast", (DL_FUNC) &_phylowise_rcpp_getNonDescendantsFast, 3},
    {"_phylowise_rcpp_nodepathFast", (DL_FUNC) &_phylowise_rcpp_nodepathFast, 3},
    {"_phylowise_rcpp_getMRCA", (DL_FUNC) &_phylowise_rcpp_getMRCA, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_phylowise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
